### ISSUE TITLE
Can't figure out the installation

### ISSUE THREAD

**Issue by CliffParker** [natdm/go-types-atom#6]
Requires GoTypelist to be downloaded and in your path.
I just can't seem to get this done as a basic user.

I tried "apm link" to no avail.

If you can add all key the GoTypelist files to the go types installation that will be great and really convenient. 
Thank you.

**Comment by natdm** [comment]
Cliff - 

Update to the newest version and see if it self-installs.

Thanks!

**Comment by natdm** [comment]
Closing from inactivity

**Comment by Nicolab** [comment]
Hello,

go-typelist seems broken:

```sh
# github.com/natdm/go-typelist
/media/data//dev/go/src/github.com/natdm/go-typelist/main.go:48: undefined: sort.Slice
```

go version go1.6.2 linux/amd64

**Comment by Nicolab** [comment]
It work with GO 1.9.1
